name: Auto Merge QA to Master

on:
  pull_request:
    types: [opened]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.event.pull_request.head.ref == 'qa'
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge f4630bf62a0ec4eb73e18fe74fb6043d2a2c3cb0  \
            --repo "vidyasrinivas7890/Learning" \
            --auto \
            --squash
